[tool.pylint.messages_control]
disable = [
	"missing-function-docstring",
	"missing-final-newline"
]

[tool.black]
line-length=80
target-version = ['py311']

[tool.isort]
profile = "black"
line_length = 80

[tool.pytest.ini_options]
testpaths = ["tests"]
filterwarnings = [
    "error",
    "ignore::UserWarning",
    "ignore::DeprecationWarning"
]

[tool.pylint.'MESSAGES CONTROL']
max-line-length = 120
disable = """
    possibly-used-before-assignment,
    import-error,
    wrong-import-position,
    unused-argument,
    no-name-in-module,
    invalid-name,
    undefined-variable,
    unspecified-encoding,
    broad-exception-caught,
    unused-variable
"""
