[tool.pylint.messages_control]
disable = [
	"missing-function-docstring",
	"missing-final-newline"
]

[tool.black]
line-length=80
target-version = ['py312']

[tool.isort]
profile = "black"
line_length = 80

[tool.pytest.ini_options]
testpaths = ["tests"]
filterwarnings = [
    "error",
    "ignore::UserWarning",
    "ignore::DeprecationWarning"
]
